version: '3.6'

networks:
  jenkins-net:
    driver: bridge
    attachable: true
volumes:
  docker-certs:

services:
  jenkins-service:
    build:
      context: .
      dockerfile: Dockerfile.jenkin
    restart: always
    # command: bash -c "rm -Rf ~/.docker && chmod 666 /var/run/docker.sock"
    networks:
      jenkins-net:
    volumes:
      - ./jenkins-home:/var/jenkins_home:z
      - docker-certs:/certs/client
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - 0.0.0.0:8888:8080
      - 0.0.0.0:50000:50000
    # depends_on:
    #   - docker
    extra_hosts:
    - "host.docker.internal:host-gateway"
